version: '4.3.0'

services:

  db:
    image: postgres:13.3
    container_name: posgresdb
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'