version: '4.3.0'

services:

  db:
    image: postgres:13.3
    container_name: posgresdb
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./utils/db:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'